apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laa-great-ideas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: laa-great-ideas
    spec:
      containers:
      - name: laa-great-ideas
        image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-great-ideas/laa-great-ideas:latest
        ports:
        - containerPort: 3000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: laa-great-ideas-rds-instance-output
                key: database_username

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: laa-great-ideas-rds-instance-output
                key: database_password

          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: laa-great-ideas-rds-instance-output
                key: rds_instance_address
          
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: laa-great-ideas-rds-instance-output
                key: database_name
          
          - name: SECRET_KEY_BASE
            valueFrom: 
              secretKeyRef:
                name: app-secrets
                key: secret_key_base
          
          - name: RAILS_ENV
            value: uat
          
          - name: RAILS_LOG_TO_STDOUT
            value: log
          
          - name: RAILS_SERVE_STATIC_FILES
            value: present
