apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  secret_key_base: N2NlODA4MzcwZDJjNmE3MmU5MDYxYmFhMzlkZDY4NWFiNTJlMzk2Zjk0ODM0NDg4MmI4MGU2N2EzNmZjNjJjMTFjOTkxMjE3NjMwYmI2ZmI3OTgxM2NkMWQ3YWU5MGU4NDVkYzFhNzI4ZWIwYjNiZmNjNjZmNWEzMzg1MzFjYjU=
