{{- if .Values.ingress.enabled -}}
{{- $fullName := include "laa-great-ideas.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    name: {{ include "laa-great-ideas.name" . }}
    helm.sh/chart: {{ include "laa-great-ideas.chart" . }}
    instance: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
    name: {{ include "laa-great-ideas.name" . }}
   {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ . }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
	{{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 3000
	{{- end }}
  {{- end }}
{{- end }}
