apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laa-great-ideas.fullname" . }}
type: Opaque
data:
  secret_key_base: {{ .Values.deploy.secretKey | b64enc | quote }}
  govuk_notify_api_key: {{ .Values.govuk_notify.api_key | b64enc | quote }}